### ISSUE TITLE
Country selector / listing

### ISSUE THREAD

**Issue by pksec** [ch-covid-19/self-report-frontend#13]
Next to the language selection, we could have a country selection e.g., Switzerland, India, and Mexico. Which will redirect you to the specific websites. This will bring a global reach.

**Comment by mullerch** [comment]
Info needed for each country:

- Country ISO code 
- URL
- Country name (in all languages)

The country name must of course be introduced by translations. For the others two data, we can imagine either:

- Fetch data from API / file
- Include it in the frontend sources

So far I would say that I see no reason that one instance would not reference some. Also this should not be updated that often and has no strict deadline. Therefore I would put it in the frontend code in an independant file (JSON) to be easily edited.

**Comment by pksec** [comment]
India
- country code: IN/IND
- https://covid-self-report.in/
- INDIA
  - English: India
  - German: Indien
  - Spanish: India
  - French: Inde
  - Italian: India

 https://covid-self-report.in/ uses only English language.

**Comment by pksec** [comment]
This issue is fixed!
