### ISSUE TITLE
MAP showing datapoints wrong (it mixes up all checkboxes) - when zoomed out

### ISSUE THREAD

**Issue by pksec** [ch-covid-19/self-report-frontend#26]
https://raw.githubusercontent.com/ch-covid-19-ind/datasets-ind/master/merge-all-days.csv (shows no record with covid confirmed cases) - but when you select covid confirmed case option and zoom out - you see that some data is available. But when you zoom-in it is a minute point that you cannot see or select.

I saw the same issue with Mexico. With Switzerland it is difficult to compare because you have actual confirmed cases reported.

**Comment by pksec** [comment]
A temp fix is available in https://github.com/ch-covid-19-ind/self-report-frontend/tree/always-visualize

**Comment by mullerch** [comment]
Fixed in 1.5
